export const DELETE_USERDATA_REQUEST = "DELETE_USERDATA_REQUEST";
export const DELETE_USERDATA_SUCCESS = "DELETE_USERDATA_SUCCESS";
export const DELETE_USERDATA_FAILURE = "DELETE_USERDATA_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";





export const GET_SLIDERDATA_REQUEST = "GET_SLIDERDATA_REQUEST";
export const GET_SLIDERDATA_SUCCESS = "GET_SLIDERDATA_SUCCESS";
export const GET_SLIDERDATA_FAILURE = "GET_SLIDERDATA_FAILURE";

export const POST_SILDERIMAGE_REQUEST = "POST_SLIDERIMAGE_REQUEST";
export const POST_SILDERIMAGE_SUCCESS = "POST_SLIDERIMAGE_SUCCESS";
export const POST_SILDERIMAGE_FAILURE = "POST_SLIDERIMAGE_FAILURE";

export const DELETE_SLIDERIMAGE_REQUEST = "DELETE_SLIDERIMAGE_REQUEST"
export const DELETE_SLIDERIMAGE_SUCCESS = "DELETE_SLIDERIMAGE_SUCCESS"
export const DELETE_SLIDERIMAGE_FAILURE = "DELETE_SLIDERIMAGE_FAILURE"





export const GET_OFFERDATA_REQUEST = "GET_OFFERDATA_REQUEST";
export const GET_OFFERDATA_SUCCESS = "GET_OFFERDATA_SUCCESS";
export const GET_OFFERDATA_FAILURE = "GET_OFFERDATA_FAILURE";

export const POST_OFFERIMAGE_REQUEST = "POST_OFFERIMAGE_REQUEST";
export const POST_OFFERIMAGE_SUCCESS = "POST_OFFERIMAGE_SUCCESS";
export const POST_OFFERIMAGE_FAILURE = "POST_OFFERIMAGE_FAILURE";

export const DELETE_OFFERIMAGE_REQUEST = "DELETE_OFFERIMAGE_REQUEST"
export const DELETE_OFFERIMAGE_SUCCESS = "DELETE_OFFERIMAGE_SUCCESS"
export const DELETE_OFFERIMAGE_FAILURE = "DELETE_OFFERIMAGE_FAILURE"



export const GET_HOTEL_REQUEST = "GET_HOTEL_REQUEST";
export const GET_HOTEL_SUCCESS = "GET_HOTEL_SUCCESS";
export const GET_HOTEL_FAILURE = "GET_HOTEL_FAILURE";

export const POST_HOTEL_REQUEST = "POST_HOTEL_REQUEST";
export const POST_HOTEL_SUCCESS = "POST_HOTEL_SUCCESS";
export const POST_HOTEL_FAILURE = "POST_HOTEL_FAILURE";

export const DELETE_HOTEL_REQUEST = "DELETE_HOTEL_REQUEST"
export const DELETE_HOTEL_SUCCESS = "DELETE_HOTEL_SUCCESS"
export const DELETE_HOTEL_FAILURE = "DELETE_HOTEL_FAILURE"



export const POST_EMAIL_REQUEST = "POST_EMAIL_REQUEST";
export const POST_EMAIL_SUCCESS = "POST_EMAIL_SUCCESS";
export const POST_EMAIL_FAILURE = "POST_EMAIL_FAILURE";